providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs", "python3", "python311Packages.pip"]

[phases.install]
cmds = [
    "mkdir -p public/uploads",
    "npm install",
    "pip install -r requirements.txt",
    "python3 --version"
]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npm run start"
