providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs"]
aptPkgs = ["python3", "python3-pip"]

[phases.install]
cmds = [
    "npm install",
    "pip3 install -r requirements.txt --break-system-packages",
    "python3 --version"
]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "mkdir -p public/uploads && npm run start"
