providers = ["node", "python"]

[phases.setup]
nixPkgs = ["nodejs", "python3", "python311Packages.pip"]

[phases.install]
cmds = ["npm install", "pip install -r python_requirements.txt", "python3 --version"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npm run start"
